[package]
name = "obsidian-folder-picker"
version = "0.1.0"
edition = "2021"
links = "obsidian-folder-picker"
build = "build.rs"

[lib]
name = "obsidian_folder_picker"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", default-features = false }

[build-dependencies]
tauri-plugin = { version = "2.6.3", features = ["build"] }
